security header tests

diff --git a/enterprise-suite/tests/smoke_nginx b/enterprise-suite/tests/smoke_nginx
--- a/enterprise-suite/tests/smoke_nginx
+++ b/enterprise-suite/tests/smoke_nginx
@@ -48,3 +48,47 @@ test_no_cache() {
 test_no_cache "${CONSOLE}/cluster"
 test_no_cache "${CONSOLE}/workloads/prometheus-server"
 test_no_cache "${CONSOLE}/service/grafana/dashboard/script/exporter-async.js?service-type=cluster"
+
+#
+# security headers
+#
+
+check_header() {
+  val=$( echo "$1" | awk -F ': ' '$1=="'"$2"'"{print $2}' )
+  if [[ -z $val ]]; then
+    echo "missing $2 header"
+    return 1
+  fi
+  if [[ $val != "$3" ]]; then
+    echo "expecting $2: $3, got \"$val\""
+    return 1
+  fi
+  return 0
+}
+
+securitay() {
+  headers=$( curl_headers "$1" )
+
+  ! echo "$headers" | grep -q "^Server: "
+  T $? "$1" has no Server header
+
+  check_header "$headers" "X-Frame-Options" "DENY"
+  T $? "$1" has X-Frame-Options
+
+  check_header "$headers" "X-XSS-Protection" "1"
+  T $? "$1" has X-XSS-Protection
+}
+
+csp() {
+  check_header "$headers" "Content-Security-Policy" "default-src 'self'; style-src 'self' 'unsafe-inline';"
+  T $? "$1" has Content-Security-Policy
+}
+
+securitay "${CONSOLE}/cluster"
+csp       "${CONSOLE}/cluster"
+securitay "${CONSOLE}/workloads/prometheus-server"
+csp       "${CONSOLE}/workloads/prometheus-server"
+securitay "${CONSOLE}/service/prometheus/"
+securitay "${CONSOLE}/service/grafana/"
+securitay "${CONSOLE}/service/alertmanager/"
+securitay "${CONSOLE}/service/es-monitor-api/"
