Allow setting charts with non-root user (#90)
By default it is unset, as there is no sensible default for this. We set it in our smoketests however, so we can verify all our pods can run as non-root to support Openshift.

This also surfaced various issues that are fixed as part of this PR:
* Need port 8080 in the nginx config for es-console.
* Bumped to es-console image `v0.1.1` which includes the fixes for non-root.
* Debug output has been improved significantly in the travis build - it should be much easier to debug broken builds now :crossed_fingers:.
* Port forward test was incorrectly using the service port, when it should be using the pod port.

Details on debug output improvement:
* Output was being interleaved due to parallel run - this is fixed by storing output in separate logs, then only displaying them on failures (in order)
* Print out a `describe` on every pod, along with its logs. This is done at the start of the tests, as well as at the end (if something fails).

part of https://github.com/lightbend/es-backend/issues/331

diff --git a/enterprise-suite/tests/smoketest b/enterprise-suite/tests/smoketest
--- a/enterprise-suite/tests/smoketest
+++ b/enterprise-suite/tests/smoketest
@@ -8,20 +8,64 @@
 FAILURES=0
 pids=()
 
+function print_debug() {
+    local pods=$(kubectl -n lightbend get pod --no-headers -o go-template='{{range .items}}{{.metadata.name}} {{end}}')
+    echo
+    echo "========================================"
+    echo "Deployment details:"
+    echo
+    for pod in $pods; do
+        echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+        echo "Describe $pod:"
+        echo
+        kubectl -n lightbend describe pod "$pod"
+        echo
+        echo "Previous logs for $pod:"
+        echo
+        kubectl -n lightbend logs -p --all-containers "$pod"
+        echo
+        echo
+        echo "Logs for $pod:"
+        echo
+        kubectl -n lightbend logs --all-containers "$pod"
+        echo
+    done
+    echo
+    echo "========================================"
+    echo
+}
+
+print_debug
+
 for smoketest in smoke_*; do
 	echo ==== Running $smoketest
 
-	./$smoketest > >(sponge /dev/stdout) &
+	./$smoketest 2>&1 > /tmp/log-$smoketest &
 	pids+=($!)
+	smoketests+=($smoketest)
 done
 
-for pid in "${pids[@]}"; do
-	wait "$pid"
-	((FAILURES+=$?))
-done
+for (( n=0; n<${#pids[@]}; n++ )); do
+    pid="${pids[$n]}"
+    smoketest="${smoketests[$n]}"
 
-# wait for all the sponge output..
-wait
+    echo -n "Waiting for $smoketest to finish... "
+    wait "$pid"
+    r=$?
+	((FAILURES+=$r))
+	if [ "$r" == "0" ]; then
+	    echo "done"
+	else
+	    echo "failed"
+	    cat /tmp/log-$smoketest
+	fi
+done
+echo
+
 echo "All tests completed with $FAILURES failures"
+
+if [ "$FAILURES" != "0" ]; then
+    print_debug
+fi
 
 exit $FAILURES
